### ISSUE TITLE
sample_data/preprocess.py reindex exception

### ISSUE THREAD

**Issue by raindrift** [HumanCompatibleAI/ranking-challenge#4]
When I run `preprocess.py`, I get this error:

```
Traceback (most recent call last):
  File "/Users/raindrift/src/ranking-challenge/sample_data/preprocessing.py", line 110, in <module>
    merged['author_name_hash'] = merged['page_id'].combine_first(merged['from_id'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/dignity-index-311/lib/python3.11/site-packages/pandas/core/series.py", line 3528, in combine_first
    this = this.reindex(keep_this, copy=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/dignity-index-311/lib/python3.11/site-packages/pandas/core/series.py", line 5144, in reindex
    return super().reindex(
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/dignity-index-311/lib/python3.11/site-packages/pandas/core/generic.py", line 5607, in reindex
    return self._reindex_axes(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/dignity-index-311/lib/python3.11/site-packages/pandas/core/generic.py", line 5630, in _reindex_axes
    new_index, indexer = ax.reindex(
                         ^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/dignity-index-311/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 4429, in reindex
    raise ValueError("cannot reindex on an axis with duplicate labels")
ValueError: cannot reindex on an axis with duplicate labels
```

If I set a breakpoint and look at the dataframe, there are a lot of ids being merged that are NaN, so perhaps that is the issue. Or there is a duplicate post/comment id someplace in the data?

**Comment by raindrift** [comment]
Wait actually let's keep bugs in tracker, that is way better. I'll move this over there.

**Comment by raindrift** [comment]
(moved to tracker)
