### ISSUE TITLE
OSError: Cannot save file into a non-existent directory: 'C:\...\ranking-challenge\sample_data\facebook_data\rrocfbsed

### ISSUE THREAD

**Issue by andaqu** [HumanCompatibleAI/ranking-challenge#6]
I tried to run `python preprocessing.py` and met the following error. Replacing `rrocfbsed` with `processed` fixed the issue.

```
C:\...\ranking-challenge\sample_data>python preprocessing.py
Traceback (most recent call last):
  File "C:\...\ranking-challenge\sample_data\preprocessing.py", line 154, in <module>
    filtered_facebook.to_csv(os.path.join(script_dir,'facebook_data/rrocfbsed/filtered_comment_post.csv'), index=False)
  File "C:\Users\andrew\AppData\Roaming\Python\Python310\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\andrew\AppData\Roaming\Python\Python310\site-packages\pandas\core\generic.py", line 3964, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "C:\Users\andrew\AppData\Roaming\Python\Python310\site-packages\pandas\io\formats\format.py", line 1014, in to_csv
    csv_formatter.save()
  File "C:\Users\andrew\AppData\Roaming\Python\Python310\site-packages\pandas\io\formats\csvs.py", line 251, in save
    with get_handle(
  File "C:\Users\andrew\AppData\Roaming\Python\Python310\site-packages\pandas\io\common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "C:\Users\andrew\AppData\Roaming\Python\Python310\site-packages\pandas\io\common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'C:\...\ranking-challenge\sample_data\facebook_data\rrocfbsed'
```

**Comment by manueltonneau** [comment]
@andaqu just create an empty subfolder entitled `rrocfbsed` in the `facebook_data` folder and it will then work!

**Comment by JACProjec** [comment]
Reverted to 'processed'. Apologies for the mixup!
